### ISSUE TITLE
Add ReadMe

### ISSUE THREAD

**Issue by Randrita** [Randrita/recognAIse#4]

**Comment by poulami08** [comment]
# recognAIse

*How many times have you desired to get an editable file instead of the traditional piece of paper you can’t work with? Let’s imagine you have a magazine article or a simply PDF and want to digitize it. Sure, you can scan the document and have it on your computer, but it won’t be editable, and you can’t make the needed changes in it. That’s when OCR software technology comes in to make your life easier.*

*Optical character recognition (OCR) technology is a business solution for automating data extraction from printed or written text from a scanned document or image file and then converting the text into a machine-readable form to be used for data processing like editing or searching.This technology helps not just digitizing documents but also improving data accessibility and enhancing file security.*


<p align="center">
  <img width="460" height="300" src="recognAlse.jpeg">
</p>

TECHSTACK
------
<p align="left">
    <img src="https://hackaday.com/wp-content/uploads/2019/09/python-logo.png" width="70" height="70">
    <img src="https://s.clipartkey.com/mpngs/s/145-1450071_flask-python-logo-transparent.png" width="80" height="80">
    <img src="https://cdn.pixabay.com/photo/2017/08/05/11/16/logo-2582748_640.png" width="80" height="80">
    <img src="https://cdn.pixabay.com/photo/2017/08/05/11/16/logo-2582747_1280.png" width="80" height="80">
    <img src="https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png" width="80" height="80">
    <img src="bootstrap.png" width="80" height="80">
    <img src="jquery.jpg" width="80" height="80">
    
</p>

APPROACH :information_desk_person:
------
*To begin, we'll use a  main template that we've made in Photoshop.* 

*We then used a couple of demo templates to extract information.
Because users will not always upload exact cropped files, we developed a method that will first detect the  key frames from the demo templates, the image will be cropped.
Following that, we identified the regions where we needed to extract texts. 
We used tesseract to extract texts and openCV to place the view on the images.*

*And it will return  a CSV file with all of the information.*



*Finally, we designed it so that users can upload files and see them on the internet.*


<p align="center">
  <img width="460" height="460" src="approch.jpeg">
</p>

CHALLENGES WE RAN INTO :confused:
------
*To begin with, we were unable to detect squares on the images in the computer vision part.We were ultimately able to solve this problem after some research.*

*Next, we had to deal with a development difficulty. Being a first time hacker we take this challenge to develop this model as well. Firstly we can't upload numerous files, and we can't return it since python can't read the picture path. It was the most difficult task for us, but with the aid of our seniors, we were able to overcome it.*

ACCOMPLISHMENTS THAT WE'RE PRODUD OF :sunglasses:
------
*The biggest accomplishment for us was that we learned so many new things in just 2 days.We were able to overcome all the challenges we faced and didn't lose hope even stayed up all night. It was tiring, but fun as well.*

DEVELOPERS
------


[![LinkedIn Badge](https://img.shields.io/badge/LinkedIn-Randrita-informational?style=flat&logo=linkedin&logoColor=white&color=0D76A8)](https://www.linkedin.com/in/randrita-sarkar-8690591a1/) 
[![LinkedIn Badge](https://img.shields.io/badge/LinkedIn-Poulami-informational?style=flat&logo=linkedin&logoColor=white&color=0D76A8)](https://www.linkedin.com/in/poulami-mandal-524390195/) 

![End](https://camo.githubusercontent.com/6e2c2f5190c42e4ff6bbd45acf48536ef9bf9e95ad599c59473cf1c701236984/68747470733a2f2f737465656d6974696d616765732e636f6d2f3078302f68747470733a2f2f63646e2e6c6966656861636b65722e72752f77702d636f6e74656e742f75706c6f6164732f323031372f30312f657a6769662e636f6d2d63726f705f313438343536333835392e676966) 

Project Demo https://bit.ly/3yUgFdw :octocat:

THANK YOU :tada:
--------------------------------
<p align="center"  >
    <meta charset="UTF-8">
    <i> “Make it work, make it right, make it fast.” &#128151 </i>
</p>
